name: Frontend workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - 'NucleicAcidConverter.Client/*'
      - '.github/workflows/action-frontend.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./NucleicAcidConverter.Client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './NucleicAcidConverter.Client/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test