name: Frontend workflow

on:
  push:
    branches:
      - 'main'
      - 'development'
    paths:
      - 'NucleicAcidConverter.Client/*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run tests
        run: npm run test